### PR TITLE
Source table

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Putting in the draft to keep track of this work and collect comments. There will need to be a filter added to Offline when this is eventually ready I will implement that PR too.

### CODE REVIEW

**Comment by sophiemiddleton** [comment]
giani has requested a name change:

I think the name chosen is confusing
I would call it caloHitRec_n0Source
and thus the filter should be named caloHitRecN0SourceFilter

**Comment by sophiemiddleton** [comment]
@gianipez any more thoughts on this PR?

**Comment by sophiemiddleton** [comment]
- checking on this again.....

**Comment by gianipez** [comment]
Hi there, before starting any review I think @sophiemiddleton needs to do a rebase because I see many changes in various files that shouldn't be present and many white-spaces added in various places. It might be simpler making a new one from scratch?

**Comment by sophiemiddleton** [comment]
Yes, I have done a rebase in the past. Likely some changes happened since I pushed this in. My changes are very simple and fairly obvious. Let me see what I can do.

**Comment by sophiemiddleton** [comment]
https://github.com/Mu2e/mu2e_trig_config/pull/37 is the new PR because I could not push to this without keeping the other +/-. I will wait for @brownd1978 to reassign the PR and then you can close this one

**Pull request closed without merging**
